@echo off
echo Japanese RO Client
echo -------------------------------
echo System:
luadec.exe ".\data\luafiles514\System\iteminfo.lub" > ".\data\luafiles514\System\iteminfo.lua"
echo -------------------------------
echo Switching to data\luafiles514\
echo -------------------------------
echo data\luafiles514\datainfo:
luadec.exe ".\data\luafiles514\datainfo\spriterobeid.lub" > ".\data\luafiles514\decoded\datainfo\spriterobeid.lub"
luadec.exe ".\data\luafiles514\datainfo\spriterobename.lub" > ".\data\luafiles514\decoded\datainfo\spriterobename.lub"
echo -------------------------------
echo data\luafiles514\effecttool:
luadec.exe ".\data\luafiles514\effecttool\1@def03.lub" > ".\data\luafiles514\decoded\effecttool\1@def03.lub"
luadec.exe ".\data\luafiles514\effecttool\1@dth1.lub" > ".\data\luafiles514\decoded\effecttool\1@dth1.lub"
luadec.exe ".\data\luafiles514\effecttool\1@dth2.lub" > ".\data\luafiles514\decoded\effecttool\1@dth2.lub"
luadec.exe ".\data\luafiles514\effecttool\1@dth3.lub" > ".\data\luafiles514\decoded\effecttool\1@dth3.lub"
luadec.exe ".\data\luafiles514\effecttool\1@eom.lub" > ".\data\luafiles514\decoded\effecttool\1@eom.lub"
luadec.exe ".\data\luafiles514\effecttool\1@jtb.lub" > ".\data\luafiles514\decoded\effecttool\1@jtb.lub"
luadec.exe ".\data\luafiles514\effecttool\1@lab.lub" > ".\data\luafiles514\decoded\effecttool\1@lab.lub"
luadec.exe ".\data\luafiles514\effecttool\1@tnm2.lub" > ".\data\luafiles514\decoded\effecttool\1@tnm2.lub"
luadec.exe ".\data\luafiles514\effecttool\1@tnm3.lub" > ".\data\luafiles514\decoded\effecttool\1@tnm3.lub"
luadec.exe ".\data\luafiles514\effecttool\effecttoolutil.lub" > ".\data\luafiles514\decoded\effecttool\effecttoolutil.lub"
luadec.exe ".\data\luafiles514\effecttool\malangdo.lub" > ".\data\luafiles514\decoded\effecttool\malangdo.lub"
luadec.exe ".\data\luafiles514\effecttool\moro_vol.lub" > ".\data\luafiles514\decoded\effecttool\moro_vol.lub"
luadec.exe ".\data\luafiles514\effecttool\verus01.lub" > ".\data\luafiles514\decoded\effecttool\verus01.lub"
luadec.exe ".\data\luafiles514\effecttool\verus03.lub" > ".\data\luafiles514\decoded\effecttool\verus03.lub"
echo -------------------------------
echo data\luafiles514\lua files:
luadec.exe ".\data\luafiles514\lua files\common.lub" > ".\data\luafiles514\decoded\lua files\common.lub"
luadec.exe ".\data\luafiles514\lua files\hotkey.lub" > ".\data\luafiles514\decoded\lua files\hotkey.lub"
luadec.exe ".\data\luafiles514\lua files\hotkey_jp.lub" > ".\data\luafiles514\decoded\lua files\hotkey_jp.lub"
luadec.exe ".\data\luafiles514\lua files\msgstring_jp.lub" > ".\data\luafiles514\decoded\lua files\msgstring_jp.lub"
luadec.exe ".\data\luafiles514\lua files\SignBoardList.lub" > ".\data\luafiles514\decoded\lua files\SignBoardList.lub"
luadec.exe ".\data\luafiles514\lua files\SignBoardList_F.lub" > ".\data\luafiles514\decoded\lua files\SignBoardList_F.lub"
luadec.exe ".\data\luafiles514\lua files\wndinfo.lub" > ".\data\luafiles514\decoded\lua files\wndinfo.lub"
echo -------------------------------
echo data\luafiles514\lua files\admin:
luadec.exe ".\data\luafiles514\lua files\admin\pcidentity.lub" > ".\data\luafiles514\decoded\lua files\admin\pcidentity.lub"
echo -------------------------------
echo data\luafiles514\lua files\chatwndinfo:
luadec.exe ".\data\luafiles514\lua files\chatwndinfo\chatwndinfo.lub" > ".\data\luafiles514\decoded\lua files\chatwndinfo\chatwndinfo.lub"
luadec.exe ".\data\luafiles514\lua files\chatwndinfo\chatwndinfo_f.lub" > ".\data\luafiles514\decoded\lua files\chatwndinfo\chatwndinfo_f.lub"
echo -------------------------------
echo data\luafiles514\lua files\datainfo:
luadec.exe ".\data\luafiles514\lua files\datainfo\accessoryid.lub" > ".\data\luafiles514\decoded\lua files\datainfo\accessoryid.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\accname.lub" > ".\data\luafiles514\decoded\lua files\datainfo\accname.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\accname_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\accname_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\addrandomoption_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\addrandomoption_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\addrandomoptionnametable.lub" > ".\data\luafiles514\decoded\lua files\datainfo\addrandomoptionnametable.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\EnumVar.lub" > ".\data\luafiles514\decoded\lua files\datainfo\EnumVar.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\JobIdentity.lub" > ".\data\luafiles514\decoded\lua files\datainfo\JobIdentity.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\jobname.lub" > ".\data\luafiles514\decoded\lua files\datainfo\jobname.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\jobname_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\jobname_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\kaframovemapservicelist.lub" > ".\data\luafiles514\decoded\lua files\datainfo\kaframovemapservicelist.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\kaframovemapservicelist_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\kaframovemapservicelist_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\LapineDdukDDakBox.lub" > ".\data\luafiles514\decoded\lua files\datainfo\LapineDdukDDakBox.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\LapineUpgradeBox.lub" > ".\data\luafiles514\decoded\lua files\datainfo\LapineUpgradeBox.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\npcidentity.lub" > ".\data\luafiles514\decoded\lua files\datainfo\NPCIdentity.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\npclocationradius.lub" > ".\data\luafiles514\decoded\lua files\datainfo\npclocationradius.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\npclocationradius_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\npclocationradius_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\petInfo.lub" > ".\data\luafiles514\decoded\lua files\datainfo\petInfo.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\questinfo_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\questinfo_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\ShadowTable.lub" > ".\data\luafiles514\decoded\lua files\datainfo\ShadowTable.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\shadowtable_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\shadowtable_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\spriterobeid.lub" > ".\data\luafiles514\decoded\lua files\datainfo\spriterobeid.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\spriterobename.lub" > ".\data\luafiles514\decoded\lua files\datainfo\spriterobename.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\spriterobename_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\spriterobename_f.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\TB_Layer_Priority.lub" > ".\data\luafiles514\decoded\lua files\datainfo\TB_Layer_Priority.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\TitleTable.lub" > ".\data\luafiles514\decoded\lua files\datainfo\TitleTable.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\weapontable.lub" > ".\data\luafiles514\decoded\lua files\datainfo\weapontable.lub"
luadec.exe ".\data\luafiles514\lua files\datainfo\weapontable_f.lub" > ".\data\luafiles514\decoded\lua files\datainfo\weapontable_f.lub"
echo -------------------------------
echo data\luafiles514\lua files\dressroom:
luadec.exe ".\data\luafiles514\lua files\dressroom\dress_f.lub" > ".\data\luafiles514\decoded\lua files\dressroom\dress_f.lub"
luadec.exe ".\data\luafiles514\lua files\dressroom\jobDressList.lub" > ".\data\luafiles514\decoded\lua files\dressroom\jobDressList.lub"
echo -------------------------------
echo data\luafiles514\lua files\effecttool:
luadec.exe ".\data\luafiles514\lua files\effecttool\1@colo.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@colo.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@cor_a.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@cor_a.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@cor_b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@cor_b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@ct_01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@ct_01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@ct_04.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@ct_04.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@ct_07.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@ct_07.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@ct_42.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@ct_42.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@ct_43.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@ct_43.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@def03.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@def03.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@dth1.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@dth1.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@dth2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@dth2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@dth3.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@dth3.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@eom.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@eom.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@eom_jp.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@eom_jp.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@gol1.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@gol1.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@gol1b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@gol1b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@gol2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@gol2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@gol2b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@gol2b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@jitter.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@jitter.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@jtb.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@jtb.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@lab.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@lab.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@ma_b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@ma_b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@mir.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@mir.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@pab.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@pab.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@pda.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@pda.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@pdb.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@pdb.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@pop1.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@pop1.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@pop3.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@pop3.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@slw.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@slw.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@sthb.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@sthb.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@sthc.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@sthc.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@sthd.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@sthd.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@swat.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@swat.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@tnm1.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@tnm1.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@tnm2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@tnm2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1@tnm3.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1@tnm3.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat_01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat_01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat_04.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat_04.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat_07.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat_07.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat_42.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat_42.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat_43.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat_43.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat101.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat101.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat104.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat104.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat107.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat107.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat142.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat142.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat143.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat143.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat201.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat201.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat204.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat204.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat207.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat207.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat242.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat242.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat243.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat243.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat301.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat301.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat304.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat304.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat307.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat307.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat342.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat342.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat343.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat343.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat401.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat401.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat404.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat404.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat407.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat407.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat442.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat442.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_tiamat443.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_tiamat443.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue1_01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue1_01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue1_04.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue1_04.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue1_07.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue1_07.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue1_42.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue1_42.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue1_43.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue1_43.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue2_01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue2_01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue2_04.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue2_04.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue2_07.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue2_07.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue2_42.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue2_42.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\1_venue2_43.lub" > ".\data\luafiles514\decoded\lua files\effecttool\1_venue2_43.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@la_06.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@la_06.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@la_25.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@la_25.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@la_31.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@la_31.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lb_06.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lb_06.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lb_25.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lb_25.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lb_31.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lb_31.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_06.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_06.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_19.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_19.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_24.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_24.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_25.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_25.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_26.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_26.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_27.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_27.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_29.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_29.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@lc_31.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@lc_31.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@mir.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@mir.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@slw.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@slw.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\2@swat.lub" > ".\data\luafiles514\decoded\lua files\effecttool\2@swat.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\3@la_00.lub" > ".\data\luafiles514\decoded\lua files\effecttool\3@la_00.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\3@lb_00.lub" > ".\data\luafiles514\decoded\lua files\effecttool\3@lb_00.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\3@lc_00.lub" > ".\data\luafiles514\decoded\lua files\effecttool\3@lc_00.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\5@lc_00.lub" > ".\data\luafiles514\decoded\lua files\effecttool\5@lc_00.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base100.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base100.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base101.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base101.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base102.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base102.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base103.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base103.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base104.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base104.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base105.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base105.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base106.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base106.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base107.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base107.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base108.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base108.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base109.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base109.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base110.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base110.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base111.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base111.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base112.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base112.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base113.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base113.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base114.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base114.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base115.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base115.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base116.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base116.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base117.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base117.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base118.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base118.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base119.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base119.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base120.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base120.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base121.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base121.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base122.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base122.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base123.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base123.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base124.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base124.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base125.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base125.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base126.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base126.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base127.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base127.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base128.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base128.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base129.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base129.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base130.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base130.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base131.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base131.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base132.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base132.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base133.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base133.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base134.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base134.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base135.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base135.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base136.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base136.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base137.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base137.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base138.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base138.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base139.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base139.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base140.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base140.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base141.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base141.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base142.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base142.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base143.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base143.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base144.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base144.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base145.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base145.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base146.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base146.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base147.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base147.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base148.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base148.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base149.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base149.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base150.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base150.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base151.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base151.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base152.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base152.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base153.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base153.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base154.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base154.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base155.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base155.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base156.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base156.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base157.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base157.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base158.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base158.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base159.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base159.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base160.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base160.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base161.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base161.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base162.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base162.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base163.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base163.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base164.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base164.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base165.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base165.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base166.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base166.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base167.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base167.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base168.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base168.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base169.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base169.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base170.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base170.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base171.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base171.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base172.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base172.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base173.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base173.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base174.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base174.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base175.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base175.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base176.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base176.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base177.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base177.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base178.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base178.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base179.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base179.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base180.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base180.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base181.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base181.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base182.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base182.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base183.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base183.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base184.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base184.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base185.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base185.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base186.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base186.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base187.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base187.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base188.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base188.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base189.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base189.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base190.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base190.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base191.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base191.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base192.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base192.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base193.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base193.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base194.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base194.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base195.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base195.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base196.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base196.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base197.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base197.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base198.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base198.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base199.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base199.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base200.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base200.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base201.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base201.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base202.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base202.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base203.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base203.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base204.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base204.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base205.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base205.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base206.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base206.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base207.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base207.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base208.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base208.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base209.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base209.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base210.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base210.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base211.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base211.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base212.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base212.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base213.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base213.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base214.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base214.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base215.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base215.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base216.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base216.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base217.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base217.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base218.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base218.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base219.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base219.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base220.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base220.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base221.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base221.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base222.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base222.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base223.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base223.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base224.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base224.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base225.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base225.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base226.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base226.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base227.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base227.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base228.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base228.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base229.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base229.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base230.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base230.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base231.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base231.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base232.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base232.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base233.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base233.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base234.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base234.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base235.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base235.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base236.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base236.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base237.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base237.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base238.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base238.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base239.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base239.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base240.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base240.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base241.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base241.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base242.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base242.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base243.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base243.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base244.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base244.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base245.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base245.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base246.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base246.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base247.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base247.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base248.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base248.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base249.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base249.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base250.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base250.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base251.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base251.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base252.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base252.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base253.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base253.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base254.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base254.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base255.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base255.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base256.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base256.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base257.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base257.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base258.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base258.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base259.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base259.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base260.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base260.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base261.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base261.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base262.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base262.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base263.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base263.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base264.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base264.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base265.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base265.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base266.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base266.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base267.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base267.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base268.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base268.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base269.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base269.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base270.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base270.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base271.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base271.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base272.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base272.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base273.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base273.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base274.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base274.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base275.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base275.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base276.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base276.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base277.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base277.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base278.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base278.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base279.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base279.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base280.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base280.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base281.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base281.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base282.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base282.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base283.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base283.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base284.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base284.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base285.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base285.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base286.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base286.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base287.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base287.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base288.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base288.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base289.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base289.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base290.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base290.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base291.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base291.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base292.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base292.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base293.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base293.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base294.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base294.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base295.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base295.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base296.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base296.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base297.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base297.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base298.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base298.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base299.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base299.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base300.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base300.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base301.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base301.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base302.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base302.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base303.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base303.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base304.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base304.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base305.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base305.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base306.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base306.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base307.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base307.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base308.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base308.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base309.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base309.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base310.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base310.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base311.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base311.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base312.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base312.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base313.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base313.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base314.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base314.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base315.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base315.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base316.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base316.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base317.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base317.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base318.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base318.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base319.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base319.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base320.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base320.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base321.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base321.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base322.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base322.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base323.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base323.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base324.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base324.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base325.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base325.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base326.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base326.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base327.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base327.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base328.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base328.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base329.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base329.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base330.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base330.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base331.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base331.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base332.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base332.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base333.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base333.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base334.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base334.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base335.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base335.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base336.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base336.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base337.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base337.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base338.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base338.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base339.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base339.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base340.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base340.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base341.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base341.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base342.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base342.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base343.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base343.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base344.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base344.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base345.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base345.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base346.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base346.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base347.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base347.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base348.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base348.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base349.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base349.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base350.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base350.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base351.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base351.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base352.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base352.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base353.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base353.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base354.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base354.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base355.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base355.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base356.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base356.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base357.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base357.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base358.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base358.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base359.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base359.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base360.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base360.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base361.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base361.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base362.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base362.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base363.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base363.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base364.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base364.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base365.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base365.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base366.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base366.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base367.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base367.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base368.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base368.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base369.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base369.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base370.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base370.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base371.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base371.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base372.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base372.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base373.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base373.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base374.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base374.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base375.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base375.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base376.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base376.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base377.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base377.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base378.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base378.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base379.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base379.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base380.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base380.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base381.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base381.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base382.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base382.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base383.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base383.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base384.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base384.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base385.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base385.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base386.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base386.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base387.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base387.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base388.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base388.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base389.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base389.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base390.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base390.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base391.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base391.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base392.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base392.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base393.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base393.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base394.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base394.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base395.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base395.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base396.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base396.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base397.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base397.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base398.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base398.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\base399.lub" > ".\data\luafiles514\decoded\lua files\effecttool\base399.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu02a.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu02a.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu02b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu02b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu02c.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu02c.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu02d.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu02d.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu02e.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu02e.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu06a.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu06a.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu06b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu06b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu06c.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu06c.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu06d.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu06d.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu06e.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu06e.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu07a.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu07a.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu07b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu07b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu07c.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu07c.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu07d.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu07d.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\do_tu07e.lub" > ".\data\luafiles514\decoded\lua files\effecttool\do_tu07e.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\effectfunc.lub" > ".\data\luafiles514\decoded\lua files\effecttool\effectfunc.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\effectmsgid.lub" > ".\data\luafiles514\decoded\lua files\effecttool\effectmsgid.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\effecttoolutil.lub" > ".\data\luafiles514\decoded\lua files\effecttool\effecttoolutil.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\effecttoolutil_ver_2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\effecttoolutil_ver_2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\har_in01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\har_in01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\harboro1.lub" > ".\data\luafiles514\decoded\lua files\effecttool\harboro1.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\harboro2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\harboro2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\harboro3.lub" > ".\data\luafiles514\decoded\lua files\effecttool\harboro3.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\job_gun.lub" > ".\data\luafiles514\decoded\lua files\effecttool\job_gun.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map05.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map05.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map06.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map06.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map07.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map07.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map08.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map08.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map09.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map09.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map10.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map10.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map11.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map11.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map17.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map17.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map25.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map25.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map26.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map26.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map38.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map38.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map40.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map40.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map53.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map53.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map54.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map54.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map55.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map55.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map56.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map56.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map58.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map58.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map61.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map61.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map64.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map64.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\jp_ev_map65.lub" > ".\data\luafiles514\decoded\lua files\effecttool\jp_ev_map65.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\lasa_dun01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\lasa_dun01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\lasa_dun02.lub" > ".\data\luafiles514\decoded\lua files\effecttool\lasa_dun02.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\lasa_dun03.lub" > ".\data\luafiles514\decoded\lua files\effecttool\lasa_dun03.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\lasagna.lub" > ".\data\luafiles514\decoded\lua files\effecttool\lasagna.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\ma_scene01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\ma_scene01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\mag_dun03.lub" > ".\data\luafiles514\decoded\lua files\effecttool\mag_dun03.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\mag_dun03a.lub" > ".\data\luafiles514\decoded\lua files\effecttool\mag_dun03a.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\mag_dun03b.lub" > ".\data\luafiles514\decoded\lua files\effecttool\mag_dun03b.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\malangdo.lub" > ".\data\luafiles514\decoded\lua files\effecttool\malangdo.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\mir_q.lub" > ".\data\luafiles514\decoded\lua files\effecttool\mir_q.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\moro_cav.lub" > ".\data\luafiles514\decoded\lua files\effecttool\moro_cav.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\moro_vol.lub" > ".\data\luafiles514\decoded\lua files\effecttool\moro_vol.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\morocc.lub" > ".\data\luafiles514\decoded\lua files\effecttool\morocc.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pab_arena.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pab_arena.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pab_camp.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pab_camp.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\paramk.lub" > ".\data\luafiles514\decoded\lua files\effecttool\paramk.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pay_d03_i.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pay_d03_i.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prontera.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prontera.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pronterar.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pronterar.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pronterar2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pronterar2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pronterar3.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pronterar3.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pronterar4.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pronterar4.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pronterar5.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pronterar5.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_cas.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_cas.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_cas_q.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_cas_q.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_chr.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_chr.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_inr.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_inr.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_lib.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_lib.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_lib_q.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_lib_q.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_mz03_i.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_mz03_i.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_mz03_q.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_mz03_q.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_prison.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_prison.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_q.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_q.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\prt_q_jp.lub" > ".\data\luafiles514\decoded\lua files\effecttool\prt_q_jp.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pub_cat.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pub_cat.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\pud_land.lub" > ".\data\luafiles514\decoded\lua files\effecttool\pud_land.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\que_swat.lub" > ".\data\luafiles514\decoded\lua files\effecttool\que_swat.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\reb_base.lub" > ".\data\luafiles514\decoded\lua files\effecttool\reb_base.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\rebel_in.lub" > ".\data\luafiles514\decoded\lua files\effecttool\rebel_in.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\rockrdg1.lub" > ".\data\luafiles514\decoded\lua files\effecttool\rockrdg1.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\rockrdg1_q.lub" > ".\data\luafiles514\decoded\lua files\effecttool\rockrdg1_q.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\rockrdg2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\rockrdg2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\rockrdg2_q.lub" > ".\data\luafiles514\decoded\lua files\effecttool\rockrdg2_q.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\slabw01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\slabw01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\slabw01_jp.lub" > ".\data\luafiles514\decoded\lua files\effecttool\slabw01_jp.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\slabw01_jp2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\slabw01_jp2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\slabw01_jp3.lub" > ".\data\luafiles514\decoded\lua files\effecttool\slabw01_jp3.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\slabw01_qjp.lub" > ".\data\luafiles514\decoded\lua files\effecttool\slabw01_qjp.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\sp_cor.lub" > ".\data\luafiles514\decoded\lua files\effecttool\sp_cor.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\sp_rudus.lub" > ".\data\luafiles514\decoded\lua files\effecttool\sp_rudus.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\sp_rudus2.lub" > ".\data\luafiles514\decoded\lua files\effecttool\sp_rudus2.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\sp_rudus3.lub" > ".\data\luafiles514\decoded\lua files\effecttool\sp_rudus3.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\t_crack.lub" > ".\data\luafiles514\decoded\lua files\effecttool\t_crack.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\tur_d03_i.lub" > ".\data\luafiles514\decoded\lua files\effecttool\tur_d03_i.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\tur_d03_j.lub" > ".\data\luafiles514\decoded\lua files\effecttool\tur_d03_j.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\tur_d04_i.lub" > ".\data\luafiles514\decoded\lua files\effecttool\tur_d04_i.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\tur_d04_j.lub" > ".\data\luafiles514\decoded\lua files\effecttool\tur_d04_j.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\verus01.lub" > ".\data\luafiles514\decoded\lua files\effecttool\verus01.lub"
luadec.exe ".\data\luafiles514\lua files\effecttool\verus03.lub" > ".\data\luafiles514\decoded\lua files\effecttool\verus03.lub"
echo -------------------------------
echo data\luafiles514\lua files\emotion:
luadec.exe ".\data\luafiles514\lua files\emotion\emotionlist.lub" > ".\data\luafiles514\decoded\lua files\emotion\emotionlist.lub"
luadec.exe ".\data\luafiles514\lua files\emotion\emotionlist_f.lub" > ".\data\luafiles514\decoded\lua files\emotion\emotionlist_f.lub"
echo -------------------------------
echo data\luafiles514\lua files\HatEffectInfo:
luadec.exe ".\data\luafiles514\lua files\HatEffectInfo\HatEffectInfo.lub" > ".\data\luafiles514\decoded\lua files\HatEffectInfo\HatEffectInfo.lub"
echo -------------------------------
echo data\luafiles514\lua files\japanlua:
luadec.exe ".\data\luafiles514\lua files\japanlua\eventmaplist.lub" > ".\data\luafiles514\decoded\lua files\japanlua\eventmaplist.lub"
echo -------------------------------
echo data\luafiles514\lua files\mapeffectinfo:
luadec.exe ".\data\luafiles514\lua files\mapeffectinfo\mapeffecttable.lub" > ".\data\luafiles514\decoded\lua files\mapeffectinfo\mapeffecttable.lub"
echo -------------------------------
echo data\luafiles514\lua files\offsetitempos:
luadec.exe ".\data\luafiles514\lua files\offsetitempos\offsetitempos.lub" > ".\data\luafiles514\decoded\lua files\offsetitempos\offsetitempos.lub"
luadec.exe ".\data\luafiles514\lua files\offsetitempos\offsetitempos_f.lub" > ".\data\luafiles514\decoded\lua files\offsetitempos\offsetitempos_f.lub"
echo -------------------------------
echo data\luafiles514\lua files\optioninfo:
luadec.exe ".\data\luafiles514\lua files\optioninfo\cmdinfo.lub" > ".\data\luafiles514\decoded\lua files\optioninfo\cmdinfo.lub"
luadec.exe ".\data\luafiles514\lua files\optioninfo\optioninfo_f.lub" > ".\data\luafiles514\decoded\lua files\optioninfo\optioninfo_f.lub"
echo -------------------------------
echo data\luafiles514\lua files\ridingspreditinfo:
luadec.exe ".\data\luafiles514\lua files\ridingspreditinfo\ridingspreditinfo.lub" > ".\data\luafiles514\decoded\lua files\ridingspreditinfo\ridingspreditinfo.lub"
luadec.exe ".\data\luafiles514\lua files\ridingspreditinfo\ridingspreditinfo_f.lub" > ".\data\luafiles514\decoded\lua files\ridingspreditinfo\ridingspreditinfo_f.lub"
echo -------------------------------
echo data\luafiles514\lua files\seekparty:
luadec.exe ".\data\luafiles514\lua files\seekparty\party_booking_config.lub" > ".\data\luafiles514\decoded\lua files\seekparty\party_booking_config.lub"
luadec.exe ".\data\luafiles514\lua files\seekparty\party_booking_function.lub" > ".\data\luafiles514\decoded\lua files\seekparty\party_booking_function.lub"
echo -------------------------------
echo data\luafiles514\lua files\service_japan:
luadec.exe ".\data\luafiles514\lua files\service_japan\ExternalSettings_jp.lub" > ".\data\luafiles514\decoded\lua files\service_japan\ExternalSettings_jp.lub"
luadec.exe ".\data\luafiles514\lua files\service_japan\externalsettings_jp_urdr.lub" > ".\data\luafiles514\decoded\lua files\service_japan\externalsettings_jp_urdr.lub"
echo -------------------------------
echo data\luafiles514\lua files\skilleffectinfo:
luadec.exe ".\data\luafiles514\lua files\skilleffectinfo\actorstate.lub" > ".\data\luafiles514\decoded\lua files\skilleffectinfo\actorstate.lub"
luadec.exe ".\data\luafiles514\lua files\skilleffectinfo\effectid.lub" > ".\data\luafiles514\decoded\lua files\skilleffectinfo\effectid.lub"
luadec.exe ".\data\luafiles514\lua files\skilleffectinfo\skilleffectinfo_f.lub" > ".\data\luafiles514\decoded\lua files\skilleffectinfo\skilleffectinfo_f.lub"
luadec.exe ".\data\luafiles514\lua files\skilleffectinfo\skilleffectinfolist.lub" > ".\data\luafiles514\decoded\lua files\skilleffectinfo\skilleffectinfolist.lub"
echo -------------------------------
echo data\luafiles514\lua files\skillinfoz:
luadec.exe ".\data\luafiles514\lua files\skillinfoz\jobinheritlist.lub" > ".\data\luafiles514\decoded\lua files\skillinfoz\jobinheritlist.lub"
luadec.exe ".\data\luafiles514\lua files\skillinfoz\skilldescript.lub" > ".\data\luafiles514\decoded\lua files\skillinfoz\skilldescript.lub"
luadec.exe ".\data\luafiles514\lua files\skillinfoz\skillid.lub" > ".\data\luafiles514\decoded\lua files\skillinfoz\skillid.lub"
luadec.exe ".\data\luafiles514\lua files\skillinfoz\SkillInfo_F.lub" > ".\data\luafiles514\decoded\lua files\skillinfoz\SkillInfo_F.lub"
luadec.exe ".\data\luafiles514\lua files\skillinfoz\skillinfolist.lub" > ".\data\luafiles514\decoded\lua files\skillinfoz\skillinfolist.lub"
luadec.exe ".\data\luafiles514\lua files\skillinfoz\skilltreeview.lub" > ".\data\luafiles514\decoded\lua files\skillinfoz\skilltreeview.lub"
echo -------------------------------
echo data\luafiles514\lua files\spreditinfo:
luadec.exe ".\data\luafiles514\lua files\spreditinfo\_new_2dlayerdir_f.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\_new_2dlayerdir_f.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\_new_biglayerdir_female.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\_new_biglayerdir_female.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\_new_biglayerdir_male.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\_new_biglayerdir_male.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\_new_smalllayerdir_female.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\_new_smalllayerdir_female.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\_new_smalllayerdir_male.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\_new_smalllayerdir_male.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\2dlayerdir_f.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\2dlayerdir_f.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\biglayerdir_female.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\biglayerdir_female.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\biglayerdir_male.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\biglayerdir_male.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\smalllayerdir_female.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\smalllayerdir_female.lub"
luadec.exe ".\data\luafiles514\lua files\spreditinfo\smalllayerdir_male.lub" > ".\data\luafiles514\decoded\lua files\spreditinfo\smalllayerdir_male.lub"
echo -------------------------------
echo data\luafiles514\lua files\stateicon:
luadec.exe ".\data\luafiles514\lua files\stateicon\efstids.lub" > ".\data\luafiles514\decoded\lua files\stateicon\efstids.lub"
luadec.exe ".\data\luafiles514\lua files\stateicon\stateiconimginfo.lub" > ".\data\luafiles514\decoded\lua files\stateicon\stateiconimginfo.lub"
luadec.exe ".\data\luafiles514\lua files\stateicon\stateiconinfo.lub" > ".\data\luafiles514\decoded\lua files\stateicon\stateiconinfo.lub"
luadec.exe ".\data\luafiles514\lua files\stateicon\stateiconinfo_f.lub" > ".\data\luafiles514\decoded\lua files\stateicon\stateiconinfo_f.lub"
echo -------------------------------
echo data\luafiles514\lua files\worldviewdata:
luadec.exe ".\data\luafiles514\lua files\worldviewdata\worldviewdata_f.lub" > ".\data\luafiles514\decoded\lua files\worldviewdata\worldviewdata_f.lub"
luadec.exe ".\data\luafiles514\lua files\worldviewdata\worldviewdata_info.lub" > ".\data\luafiles514\decoded\lua files\worldviewdata\worldviewdata_info.lub"
luadec.exe ".\data\luafiles514\lua files\worldviewdata\worldviewdata_language.lub" > ".\data\luafiles514\decoded\lua files\worldviewdata\worldviewdata_language.lub"
luadec.exe ".\data\luafiles514\lua files\worldviewdata\worldviewdata_list.lub" > ".\data\luafiles514\decoded\lua files\worldviewdata\worldviewdata_list.lub"
luadec.exe ".\data\luafiles514\lua files\worldviewdata\worldviewdata_table.lub" > ".\data\luafiles514\decoded\lua files\worldviewdata\worldviewdata_table.lub"
echo -------------------------------
echo Decoding completed.
pause